services:
  pocketbase:
    image: egglou/pocketbase:stable

    container_name: ${PROJECT_NAME}

    restart: unless-stopped

    expose:
      - "8090"

    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations

    env_file:
      - .env

    networks:
      - app-network

  caddy:
    image: caddy:2-alpine

    container_name: caddy

    restart: unless-stopped

    depends_on:
      - pocketbase

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    env_file:
      - .env

    networks:
      - app-network

networks:
  app-network:

volumes:
  caddy_data:
  caddy_config:
