services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PB_VERSION: ${PB_VERSION}

    container_name: ${PROJECT_NAME}

    expose:
      - "8090"

    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks:/pb/pb_hooks
      - ./pb_migrations:/pb/pb_migrations

    restart: unless-stopped

    env_file:
      - .env

    networks:
      - pocketbase-network

  caddy:
    image: caddy:2-alpine

    container_name: caddy

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

    depends_on:
      - pocketbase

    env_file:
      - .env

    networks:
      - pocketbase-network

networks:
  pocketbase-network:

volumes:
  caddy_data:
  caddy_config:
